
services:
  app:
    build:
      context: .
      dockerfile: /Dockerfile-app
    ports:
      - 8000:8000

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mystuffdb
      POSTGRES_USER: bernie
      POSTGRES_PASSWORD: l0max
    ports:
      - 5432:5432

volumes:
  postgres-data: